title: ✨ hallucinating a narrative 
email: jli@circularly.org
description: >-
  I suspect things may be even more chaotic than they seem.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: circularly
github_username: jli
show_excerpts: true
google_analytics: UA-161682654-1
home: /log # used to direct title link

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
